version: '3.9'
# version of docker-compose
services:
  app:
    build:
      context: .
      # build the docker file in current directory
      args:
        - DEV=true
        # Activate the development environment
    ports:
      - '8000:8000'
      # connect port our local machine to port 8000 inside our docker container
    volumes:
      - ./app:/app
      # sync of internal app to docker app (cloud runnin in the container)
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  # Specifies the type of command in Docker container to execute
